spring:
  datasource:
    url: ${DATABASE_URL:${MYSQL_URL:jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}}
    username: ${DB_USERNAME:${MYSQLUSER:}}
    password: ${DB_PASSWORD:${MYSQLPASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
